NAME = ft_display_file

CFLAGS = -Wall -Werror -Wextra

SRC = ft_display_file.c

OFILES = ft_cat.o

all: $(NAME)

$(NAME):
	gcc $(CFLAGS) $(SRC) -o $(NAME)

clean:
	rm -rf $(OFILES)

fclean: clean
	rm -rf $(NAME)